services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "${WEB_APP_PORT:-80}:8000"
    group_add:
      - "100"
    volumes:
      - .env:/vault-secrets/.env
#      - vault-secrets:/vault-secrets
#    depends_on:
#      vault-agent:
#        condition: service_started
    networks:
      - lct-net

  inference:
    build:
      context: .
      dockerfile: inference/Dockerfile
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]

#  vault-agent:
#    image: hashicorp/vault:1.17
#    command: agent -config=/vault-agent/agent.hcl
#    cap_add:
#      - IPC_LOCK
#    volumes:
#      - ./agent.hcl:/vault-agent/agent.hcl:ro
#      - ./env_template.ctmpl:/vault-template/template.ctmpl:ro
#      - ./role_id:/vault-auth/role_id:ro
#      - ./wrapped_secret_id:/vault-auth/wrapped_secret_id:ro
#      - vault-secrets:/vault-secrets
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    networks:
#      - lct-net

networks:
  lct-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.12.0/24

#volumes:
#  vault-secrets:
#    driver_opts:
#      type: tmpfs
#      device: tmpfs
#      o: "size=1m,mode=0777,uid=65532,gid=65532"
#  projects-data:
